version: '3.8'
services:
    postgresdb:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
    server:
        depends_on:
            - postgresdb
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3001:3001"